### ISSUE TITLE
Cannot follow a CURIES URI with a provided a namespaced relationship

### ISSUE THREAD

**Issue by jrcollins4** [petejohanson/angular-hy-res#19]
From our [Google Groups conversation](https://groups.google.com/forum/#!topic/angular-hy-res/zCmkKsT1xcs): 

I am wanting to grab (GET) the curies for a given fully-qualified relationship.  Using the below data as an example -- the curies has the namespace 'ea" set for the "name" property.  If I want to hit the curies endpoint for ea:find mid-application, there is currently no built-in way to pass in {ea:find} at that specified URI (http://example.com/docs/rels/{rel}) and for the library to know to strip out the "ea:" namespace and use only "find" as the relationship to send up as the {rel} parameter in the request URI?  

``` javascript
{
    "_links": {
        "self": { "href": "/orders" },
        "curies": [{ "name": "ea", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
        "next": { "href": "/orders?page=2" },
        "ea:find": {
            "href": "/orders{?id}",
            "templated": true
        },
        "ea:admin": [{
            "href": "/admins/2",
            "title": "Fred"
        }, {
            "href": "/admins/5",
            "title": "Kate"
        }]
    }
}
```

Let me know what I can do to help out.  I am pressed for a deadline, so unfortunately I might have to implement a workaround similar to what you mentioned in our chat in the meantime.  

Thanks a bunch for all your help!

Jeff

**Comment by petejohanson** [comment]
An important discussion on the HAL discuss group which impacts any implementation: https://groups.google.com/forum/m/#!searchin/hal-discuss/Curie/hal-discuss/A-DNfNU2Nds

Because curies MAY be defined at the root and still be in scope in deeply nested embedded resources, I think we would need the following:

1. The HyRes.Context (src/context.js) will need to support tracking curies in the current scope. When creating child contexts for embedded resources, the curie set would be inherited. Depending on final answer to my recent question on list, they might also be added/overridden by embedded resources.
1. Add a new function to the HyRes.Extension "interface" like `parseCuries` that lets extensions return curies for that scope.
1. curies instances need to actually have an API, since the actual processing of curies is format specific (e.g. HAL uses URI Templates, others may use simple concatenation). Something like `curie.expand(reference) `.
1. Add function to HyRes.Resource to expand a proper Curie, that delegates to the context, e.g. `res.$expandCurie('ea:find')`.

Thoughts?

**Comment by petejohanson** [comment]
I've started toying with some of the implementation bits of the approach I mentioned in a branch of hy-res, found here: https://github.com/petejohanson/hy-res/tree/ftr_curie_support

If you want to track progress, give feedback, etc.
