### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by jinder** [petejohanson/angular-hy-res#3]
Would it be possible to publish this as an NPM package?

**Comment by petejohanson** [comment]
Right now, this is only published as a Bower package. In order to package for NPM, this would need access to AngularJS via NPM. Last I looked, there were no *official* AngularJS NPM packages one could depend on. Has that changed?

**Comment by jinder** [comment]
Yes, there is now an official NPM package maintained by the angular team:  https://www.npmjs.com/package/angular

Also. I should perhaps raise this as a separate ticket, but it's not clear in the documentation that your library requires URI.js.  This dependency makes it difficult to use angular-hy-res with requirejs because of this:  https://github.com/medialize/URI.js/issues/118

**Comment by XVincentX** [comment]
+1

**Comment by petejohanson** [comment]
Ok, I've done a lot of work on this in a branch that I've just merged to master. I haven't yet tackled the URI.js issue, but so far this works as expected when using webpack for the karma tests, for example.

I'm going to attempt to switch https://github.com/petejohanson/angular-hy-res-example/ over to using requirejs in order to fully test the end-to-end support for this and suss out any remaining issues.

For the various angular modules, I've taken the approach that the Angular core team took, which is to export the *module name* for the given file, e.g.:

```javascript
var angular = require('angular');
var Hal = require('hy-res').HalExtension;

angular.module('hrHal', [require('./core')])
  .provider('hrHalExtension', function() {
    this.mediaTypes = [];
    this.$get = function() {
      return new Hal(this.mediaTypes);
    };
  })
  .config(['hrRootProvider', function(hrRootProvider) {
    hrRootProvider.extensions.push('hrHalExtension');
  }]);

module.exports='hrHal';
```

The advantage being you can simply put the require in the deps section of the module declaration and it loads the required file, and then is visible in "angular land" as well.

As part of this, I've created a new toplevel Angular module, 'hrHyRes' that is in the toplevel index.js file, and depends on *all* the angular-hy-res items, so it includes HAL, Siren, Link headers, etc. in a single module/requires:

```javascript
angular.module('myMod', [ require('angular-hy-res') ]);
```

For those users looking to only use a selective set of extensions, you can instead do:

```javascript
angular.module('myMod', [
  require('angular-hy-res/hal'),
  require('angular-hy-res/json'),
]);
```
Once I get things more finalized and ready to publish the NPM package, I'll update the README accordingly.

In the meantime, AFAICT, I have still kept the bower package working as expected by using a webpack config that treats angular as an external, instead of bundling it.

Any testing of current `master` would be appreciated.

**Comment by XVincentX** [comment]
I will once I'll be back from Italy!
Thank you for the awesome work.

V.

-----Mensaje original-----
De: "Pete Johanson" <notifications@github.com>
Enviado: ‎15/‎05/‎2015 3:22
Para: "petejohanson/angular-hy-res" <angular-hy-res@noreply.github.com>
CC: "Vincenzo Chianese" <vincenz.chianese@yahoo.it>
Asunto: Re: [angular-hy-res] NPM Package (#3)

Ok, I've done a lot of work on this in a branch that I've just merged to master. I haven't yet tackled the URI.js issue, but so far this works as expected when using webpack for the karma tests, for example.
I'm going to attempt to switch https://github.com/petejohanson/angular-hy-res-example/ over to using requirejs in order to fully test the end-to-end support for this and suss out any remaining issues.
For the various angular modules, I've taken the approach that the Angular core team took, which is to export the module name for the given file, e.g.:
var angular = require('angular');
var Hal = require('hy-res').HalExtension;

angular.module('hrHal', [require('./core')])
  .provider('hrHalExtension', function() {
    this.mediaTypes = [];
    this.$get = function() {
      return new Hal(this.mediaTypes);
    };
  })
  .config(['hrRootProvider', function(hrRootProvider) {
    hrRootProvider.extensions.push('hrHalExtension');
  }]);

module.exports='hrHal';The advantage being you can simply put the require in the deps section of the module declaration and it loads the required file, and then is visible in "angular land" as well.
As part of this, I've created a new toplevel Angular module, 'hrHyRes' that is in the toplevel index.js file, and depends on all the angular-hy-res items, so it includes HAL, Siren, Link headers, etc. in a single module/requires:
angular.module('myMod', [ require('angular-hy-res') ]);For those users looking to only use a selective set of extensions, you can instead do:
angular.module('myMod', [
  require('angular-hy-res/hal'),
  require('angular-hy-res/json'),
]);Once I get things more finalized and ready to publish the NPM package, I'll update the README accordingly.
In the meantime, AFAICT, I have still kept the bower package working as expected by using a webpack config that treats angular as an external, instead of bundling it.
Any testing of current master would be appreciated.

**Comment by XVincentX** [comment]
@petejohanson 
Great improvements here, congrats.
BTW, I think there is another improvement to do yet.
Since your package is now available from both npm and bower, your way to use angular dependency should vary.

If you cannot detect any module system, then you can rely to the fact that angular global object is already exposed. But if you can find that your file is being [required](https://github.com/auth0/winchan/blob/master/winchan.js#L299), you should load angular as a dependency and then go on.

**Comment by petejohanson** [comment]
My thinking was the following:

* The NPM module does *not* use `dist` at all, and uses the sources in the top level folder as checked in directly. That means angular is pulled from the `require('angular')` and no globals are used. Consumers using `requirejs` or `browserify` thus can use this NPM module and angular will be injected from the hosting environment as expected.
* `dist` exists solely for the bower package, so for that we webpack our 'internal' NPM dependencies (as before), but configure webpack to keep angular 'external'. Since the bower package of angular explicitly assigns `window.angular`, I think this approach works for the bower case.

Am I missing something? I am admittedly not an experienced JS dev, so please feel free to correct.any errors/misunderstandings on my part.

**Comment by XVincentX** [comment]
Hey,
your explanation is very clear and the things should be done in this way.
The last thing you should do is to specify the **main** entry into package.json. In this way, package manager (such as jspm or others) can understand the module to import and not try to guess it (using bower.json, for example).

I have prepared a [PR](https://github.com/petejohanson/angular-hy-res/pull/10). Feel free to review/merge/deploy/destroy.

**Comment by petejohanson** [comment]
Ok, I've just published an initial NPM module: https://www.npmjs.com/package/angular-hy-res as part of the 0.0.17 release also published to Bower.

Marking this closed for now, please re-open if needed.

**Comment by XVincentX** [comment]
Tried. It is working as expected.
